name = "spinmachologin-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachologin.com"
HMAC_KEY = "13956fb4379afd773d3f3218dac48cb8d0dfe961cab78d8fe12ff285b9b7503f"
COOKIE_NAME = "4c3"
PLAY_PATH = "play-now"
BUTTON_ID = "p50bf41c5bbb1fde23e4dc3a2207c72d1"
GATE_SALT = "9b17b887a2a448f1"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ufc9"
CTA_SELECTOR = ".play-button"
